language: r

sudo: required

apt_packages:
  - texlive
  - ghostscript
  - texlive-fonts-extra
  - texinfo  

notifications:
  email:
    on_success: change
    on_failure: change

env:
  - TEST_SUITE=CRAN
  - TEST_SUITE=TRAVIS

script:
  - R CMD INSTALL .
  - if [ "$TEST_SUITE" == "CRAN" ];then bash build.sh;else Rscript -e "source('tests/testthat.R', chdir = TRUE)";fi

