# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

isoreg_dp_interface <- function(data_vec) {
    .Call(`_directlabels_isoreg_dp_interface`, data_vec)
}

